[build]
  publish = "react-weather-app/build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "./public/index.html"
  status = 200

[[plugins]]
package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
  buildEvent = "onBuild"